#!/usr/bin/env bash
# script of product.

echo "num1"
read num1 
echo "num2"
read num2

ans=$(( $num1 * $num2))
echo "The product of $num1 and $num2 is $ans"
![BASH SCRIPT_LCS_CODE](https://user-images.githubusercontent.com/92328277/174792054-300a7ce2-a77f-4c42-9955-b7c4946b178f.PNG)
