#!/usr/bin/env bash
# script of product.

echo "num1"
read num1 
echo "num2"
read num2

ans=$(( $num1 * $num2))
echo "The product of $num1 and $num2 is $ans"

![BASH SCRIPT_LCS_CODE](https://user-images.githubusercontent.com/92328277/174859237-29c37173-15dd-45f4-86c6-84605a34a274.PNG)

