#!/usr/bin/env bash
#Script that takes path and confirms if it is a directory or not
echo "enter directory path"
read DIR
i=0
while [ $i -eq 0 ]
do
  if [ -d "$DIR" ]; then
	ls -la "$DIR"
	((i++))
  else
	echo "enter correct directory path"
	read DIR
  fi 
done
